# Generated by Django 5.2.7 on 2025-10-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Position')),
                ('firma', models.CharField(max_length=50, verbose_name='Firma')),
                ('firma_link', models.CharField(max_length=250, verbose_name='Link zur Firma')),
            ],
            options={
                'verbose_name': 'Stellenangebot',
                'verbose_name_plural': 'Stellenangebote',
            },
        ),
    ]
